### PR TITLE
Adding skills descriptions to be showed in Manaplus skill window

### PR DESCRIPTION
**Pull request by Cassy1**
Title says it all. Also made a few comments in the file itself.

### CODE REVIEW

**Comment by mekolat** [comment]
@Cassy1 I already planned to do this but wanted to wait for players to update their clients since 4144 recently added "invokeCmd" to the skill handler

**Comment by mekolat** [comment]
each skill can have these extra fields: useButton, owner, errorText, alwaysVisible (important for "magic" skills), shortName, particle, soundHit, soundMiss

**Comment by wushin** [comment]
Could we get some documentation about this on a wiki?

**Comment by Cassy1** [comment]
@mekolat Yes, I used alwaysVisible for the three Basic Skills. Dunno your plans for invokeCmd and others but let's get this one in for now and you can add your stuff later. For now this should already be helpful for new players.

Going to check what Travis Ci wants.

**Comment by mekolat** [comment]
My plan was to completely deprecate the "spells" window and instead use the skills window. Each magic school would be its own tab (Magic, Astral, Transmutation, ...) and each tab would contain the spells (which would now be skills). The spells will only appear in the skills window once the user "unlocks" them by learning it from the relevant npcs. The spell can then be dragged to the shortcut window to assign a hotkey.

When called through the shortcut window (either by clicking on the spell icon or by pressing the hotkey), the spell will call what is in invokeCmd so clicking on the "summon pinkie" spell would call #kalgina

**Comment by mekolat** [comment]
@wushin I wil not start documenting manaplus as it always changes so the best way to understand it is to look at the source and experiment

**Comment by mekolat** [comment]
oh and btw XML only accepts comment blocks wrapped in

**Comment by Cassy1** [comment]
@mekolat Sounds good. Might also be a good idea to get rid of spells that can be used without having to talk to the NPC who teaches it. I like it.

Yeah, I already fixed the comment lines in the XML. What's missing is the appropriate xsd file in tools. I will fix that later when I'm home.

**Comment by Cassy1** [comment]
A bit late, but here we go.

**Pull request merged**
