### PR TITLE
Clean up old emotes

### PR DESCRIPTION
**Pull request by mekolat**
* Remove traces of the legacy Mana emote system
* Add Nyahahaha emote (for future use)

### CODE REVIEW

**Comment by mekolat** [comment]
now this is just a PR to clean old emotes

**Comment by nashley** [comment]
@mekolat Why remove all these emotes? :(
I can try my hand at making them look better if you're worried about quality.

**Comment by mekolat** [comment]
@nashley I do not remove them, they are already not used anymore
they got merged into manaplus (long ago) so we remove 'em in client-data

**Comment by nashley** [comment]
@mekolat That makes more sense.

**Pull request merged**
