### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by alexanderlime**
Fluffys-> Fluffies

### CODE REVIEW

**Comment by mekolat** [comment]
@alexanderlime all variations of the beret would need to be fixed: https://github.com/themanaworld/tmwa-client-data/search?q=fluffys

**Comment by alexanderlime** [comment]
Fine.

**Comment by mekolat** [comment]
why is this closed?

**Comment by alexanderlime** [comment]
Perhaps there's something wrong in the code that made the 'test' last for a week.

**Comment by mekolat** [comment]
@alexanderlime we never merge right away. if it stays on test label it means we are not ready to make a release yet. wushin only merge when he's making a release

**Comment by mekolat** [comment]
...and by the way you are trying to merge from your master

**Comment by wushin** [comment]
Aye, leave PRs open. Someone will comment if changes are needed.

**Comment by wushin** [comment]
rebased this in #246

**Comment by wushin** [comment]
this has been merged into the code but github didn't close it.

**Pull request closed without merging**
