### PR TITLE
make mouboo dye-able

### PR DESCRIPTION
**Pull request by mekolat**
this is for the skytlurk <3

---
- Remove christmas-mouboo which is same as mouboo
- Make mouboo dye-able

---

colors extracted with Gpick

### CODE REVIEW

**Comment by wushin** [comment]
@Cassy1 can you look this over. I wanna say there is a reason we did it one way vs. another.

**Comment by Cassy1** [comment]
Just talked with meko about it: the christmas mouboo sprite must either stay or the nostrils it's missing must be added as accesoire cause otherwise the mouboo variants with a rednose would have two noses ;)

**Comment by wushin** [comment]
Agree with a Nose sprite sheet.

**Comment by mekolat** [comment]
been working on the colors for 2 fking hours T_T
I can't get to look the same as the original mouboo
I give up

**Comment by wushin** [comment]
@CandyCurt Pick some colors for Mouboo?

**Comment by TRGNTMW** [comment]
skytlurks need this
https://forums.themanaworld.org/viewtopic.php?f=4&t=18816&p=147703#p147703

**Comment by TRGNTMW** [comment]
Now we have to dye the injured mouboo, as it is grey (at least on the test server).

**Comment by mekolat** [comment]
@TRGNTMW that is no problem
as soon as we can have a good palette for the mouboo we can dye the injured mouboo

**Comment by CandyCurt** [comment]
depends if u want an exact copy of the original one or not - if so u Need
to use at least 3 channels or a *very* verbose Color ramp for that one...
(one channel dyed reddish for snout one channel Grey brownish for ears and
one for the rest in mouboo Color) dont have time for that atm

**Comment by TRGNTMW** [comment]
https://github.com/themanaworld/tmwa-client-data/pull/247

**Comment by TRGNTMW** [comment]
Why did you close it?

**Comment by mekolat** [comment]
@TRGNTMW because all the repositories of The Mana World Legacy are deprecated and will not receive any further modification, except critical patches when needed

**Pull request closed without merging**
