### PR TITLE
Some of the Tonori Area quests

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by wushin** [comment]
@nashley I know this is most likely the last thing you want to deal with more of.If ya get a chance clean up dialogue in these quests?

**Comment by mekolat** [comment]
note to self:
* tinris
* eomie
* sandra
* sarah

**Comment by wushin** [comment]
@pydsigner Any chance you could improve the dialogue options in this chunk of quest log?

**Comment by wushin** [comment]
@mekolat can you test Kylian and Mine Quests?

**Comment by mekolat** [comment]
Checklist:
- [x] banu
- [ ] soup_and_slimes
- [ ] anwar
- [ ] fieri
- [ ] imec
- [ ] kylian
- [ ] mine
- [ ] sandra
- [ ] sarah
- [ ] terranite_armor

**Comment by wushin** [comment]
@mekolat Corrected Heathin and Kylian a bit.
Without rewriting the quest we can't really do much with Kylian.
I put some ! in terranite armor where it currently pauses/breaks in the quest steps.

**Pull request merged**
