### PR TITLE
3rd gender, new races

### PR DESCRIPTION
**Pull request by mekolat**

### CODE REVIEW

**Comment by TRGNTMW** [comment]
Please stop spamming my e-mail inbox with things that aren't related to skytlurks AT ALL.

**Comment by mekolat** [comment]
@TRGNTMW just unsubscribe

**Comment by TRGNTMW** [comment]
Then i will miss important skytlurk things, as well

**Comment by mekolat** [comment]
@TRGNTMW I don't think anyone is gonna work on the skytlurk any time soon

**Comment by wushin** [comment]
@mekolat this PR is fine to go in as is.

**Pull request merged**
