### PR TITLE
fixed map 099-7 and added minimap

### PR DESCRIPTION
**Pull request by HoraK-FDF**

### CODE REVIEW

**Comment by HoraK-FDF** [comment]
can you please include it even if you said there are many changes coming to this map? Some people are really annoyed by that missing minimap and the monsters that get stuck on the small island.

**Comment by pazkero** [comment]
> can you please include it even if you said there are many changes coming to this map? Some people are really annoyed by that missing minimap and the monsters that get stuck on the small island.

The problem is that even if you fix on client, the server won't acknowledge the changes =/

Then it'll be stuck on a collision tile instead of a small island =/

**Comment by HoraK-FDF** [comment]
added chest collusion tile.
added/corrected many collusion tiles of trees.

**Comment by HoraK-FDF** [comment]
- added some collusion tiles and removed some
- turned Engraving into a stone
- added some plants
- changed some dead trees in other kinds of dead trees
- changed little pool on safe island into a camp fire because many players wished for that

**Pull request merged**
