### PR TITLE
fix: minor typos in quests messages

### PR DESCRIPTION
**Pull request by nelson6e65**

### CODE REVIEW

**Comment by mekolat** [comment]
@wushin do you *really* need to test this?
:shipit: merge

**Comment by nelson6e65** [comment]
I found another minor typo... Should do I join patch to this or make another PR?

**Comment by nelson6e65** [comment]
Wait... There is another typos...

**Comment by nelson6e65** [comment]
Done for now. :green_apple:

**Comment by wushin** [comment]
@mekolat Thats why. ^

**Comment by nelson6e65** [comment]
I don't know if there is a method to unable pull request *until done* in GitHub.

On GitLab, you add `"[WIP]"` (Work In Progress) to the title and disable the merging until title is updated (removing that prefix).

Next time, I'll add `"[WIP]"`  prefix tittle.

**Pull request merged**
