### PR TITLE
Terranite Head (5209) offset fix

### PR DESCRIPTION
**Pull request by HoraK-FDF**
fixed wrong offset for stand right/attack right and added missing offsets of other attack kinds.

### CODE REVIEW

**Comment by pazkero** [comment]
`graphics/sprites/monsters/terranite-mask.xml` → Something looks wrong O.o

**Comment by pazkero** [comment]
@HoraK-FDF could you please check the file location and correct it if needed? =/

**Comment by HoraK-FDF** [comment]
> @HoraK-FDF could you please check the file location and correct it if needed? =/
> 
> _(PS. Ignore the CI errors, I'll just tell GitHub to merge it regardless of CI status - Not advised)_

I found it on this position. I also wondered but kept it there since it was next to the terranite monster and thought this might be intended that way.

**Comment by pazkero** [comment]
Naah, if you could fix it much appreciated-- Sent from Yandex.Mail for mobile11:03, March 4, 2021, "HoraK-FDF" <notifications@github.com>:

@HoraK-FDF could you please check the file location and correct it if needed? =/
(PS. Ignore the CI errors, I'll just tell GitHub to merge it regardless of CI status - Not advised)

I found it on this position. I also wondered but kept it there since it was next to the terranite monster and thought this might be intended that way.

**Pull request merged**
